name: CI (Test and Build)
on: pull_request
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ./ui/.nvmrc

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile
        working-directory: ./ui

      # - name: Run Lint
      #   run: bun run lint
      #   working-directory: ./ui

      # - name: Run Tests
      #   run: bun run test -- run
      #   working-directory: ./ui

      - name: Build
        run: bun run build
        working-directory: ./ui
